import React from 'react';
import Head from 'next/head';
import VideoList from '@/components/VideoList';
import Video from '@/models/Video';

export default function Home() {
  const videos = [
    new Video('I9n3nzZQrS0', 'Title', 'This is a description'),
  ];

  //  ['I9n3nzZQrS0', 'WXRJ4YWvClY', 'fGyVpUgSSuA', 'jk3dwcwco2c', '49IoiZf7o_M', 'lOyHnCqWLR4'];

  return (
    <>
      <Head>
        <title>ndmvisuals | video production</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-6">
        <h1 className="text-3xl font-bold underline">ndmvisuals</h1>
        <VideoList videos={videos} />
      </main>
    </>
  );
}
