import React from 'react';
import Head from 'next/head';
import VideoCarousel from '@/components/VideoCarousel';
import Video from '@/models/Video';

export default function Home() {
  const videos = [
    new Video('I9n3nzZQrS0', 'Residence Meunier'),
    new Video('WXRJ4YWvClY', 'Inpulse Coaching'),
    new Video('fGyVpUgSSuA', 'Inpulse Coaching'),
    new Video('jk3dwcwco2c', 'Inpulse Coaching'),
    new Video('49IoiZf7o_M', 'Inpulse Coaching'),
    new Video('lOyHnCqWLR4', 'Inpulse Coaching'),
  ];

  return (
    <>
      <Head>
        <title>ndmvisuals | video production</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4">
        <VideoCarousel videos={videos} />
      </main>
    </>
  );
}
